export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
export const GET_ALL_CART_ITEM_REQUEST = 'GET_ALL_CART_ITEM_REQUEST';
export const GET_ALL_CART_ITEM_SUCCESS = 'GET_ALL_CART_ITEM_SUCCESS';
export const GET_ALL_CART_ITEM_FAIL = 'GET_ALL_CART_ITEM_FAIL';
